# Generated by Django 2.2.5 on 2019-12-09 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('idealista_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='property_pics',
            new_name='PropertyPics',
        ),
        migrations.RenameModel(
            old_name='property_type',
            new_name='PropertyType',
        ),
        migrations.AddField(
            model_name='property',
            name='address_number',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='bath',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='creation_date',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='has_elevator',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='is_exterior',
            field=models.SmallIntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='m_built',
            field=models.DecimalField(
                decimal_places=2, default=1000, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='m_use',
            field=models.DecimalField(
                decimal_places=2, default=1000, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='property',
            name='op_type',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=100000, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to='idealista_app.Location'),
        ),
        migrations.AlterField(
            model_name='propertypics',
            name='property',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='idealista_app.Property'),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='idealista_app.State')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='province',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='idealista_app.Province'),
            preserve_default=False,
        ),
    ]
