# Generated by Django 2.2.5 on 2019-12-09 12:59

from django.db import migrations, models
import django.db.models.deletion

import os


class Migration(migrations.Migration):

    dependencies = [
        ('idealista_app', '0002_auto_20191209_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to='idealista_app.Location'),
        ),
        migrations.AlterField(
            model_name='propertypics',
            name='property',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='idealista_app.Property'),
        ),
        migrations.RunSQL(open('../'))
    ]
