# Generated by Django 2.2.5 on 2019-12-10 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('acr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('op_type', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('address', models.CharField(max_length=150)),
                ('address_number', models.CharField(blank=True, max_length=5, null=True)),
                ('floor', models.CharField(blank=True, max_length=15, null=True)),
                ('door', models.CharField(blank=True, max_length=15, null=True)),
                ('m_built', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('m_use', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('bath', models.IntegerField(blank=True, null=True)),
                ('is_exterior', models.SmallIntegerField(blank=True, null=True)),
                ('has_elevator', models.SmallIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=9)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='idealista_app.Location')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('acr', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('acr', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('acr', models.CharField(max_length=100, unique=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='idealista_app.State')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idealista_app.Property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='pro_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='idealista_app.PropertyType'),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='idealista_app.Province'),
        ),
    ]
